### ISSUE TITLE
some wrong about it

### ISSUE THREAD

**Issue by caoxingshu** [niket-panjwani/code-whisper#1]
# it always show me a message:"Oops, no response was returned."

**Comment by niket-panjwani** [comment]
Hi @caoxingshu 

Thank you for bringing this issue to our attention. We sincerely apologize for any inconvenience this may have caused you. We have identified that the problem stemmed from an expired OpenAI access token and have promptly replaced it to rectify the issue. You should no longer encounter the error message you mentioned.

If you have any further questions or concerns, please don't hesitate to let us know. We appreciate your patience and understanding.

Best regards,
Niket Panjwani
